#include <iostream>
#include <iomanip>
#include <fstream>
#include <sstream>
#include <array>
#include <random>
#include <algorithm>
#include <cstddef>

#include <gdyn.hpp>
#include <rllib2.hpp>

// Read these files.
#include "discrete-rocket-problem.hpp"
#include "my_rocket_config.hpp"

// In this example, we load the controller learned previously and apply it.

// Let us implement a moving target. It consists of changing a height
// periodically (see ++). The hight is kept far from the floor and
// ceiling, this is what margin means.

// The training has been made with quite large timesteps. Let us use smaller ones here.
#define DT_FACTOR .1
struct target {
private:
  std::mt19937& gen;
  std::uniform_real_distribution<double> d;
  std::size_t period;
  std::size_t count;

public:
  double height;
  
  target(std::mt19937& gen, double margin, std::size_t period, const gdyn::problem::rocket::parameters& params)
    : gen(gen),
      d(margin, params.ceiling_height - margin),
      period(period),
      count(1) {++(*this);}

  target& operator++() {
    if(--count == 0) {
      height = d(gen);
      count = period;
    }
    return *this;
  }
};

#define TARGET_PERIOD 50 // seconds
#define MARGIN 200
#define EPISODE_DURATION 10*TARGET_PERIOD
int main(int argc, char* argv[]) {

  if(argc != 2) {
    std::cout << "Usage: " << argv[0] << " <controller-datafile.dat>" << std::endl
	      << "       The datafile is generated by previous example." << std::endl;
    return 0;
  }
  
  std::random_device rd;
  std::mt19937 gen(rd());

  double dt = types::dt * DT_FACTOR;
  std::size_t target_period = std::size_t(TARGET_PERIOD / dt);

  // This stores the thrusts associated to each (error, speed)
  // computed previously. We get them from a .dat file.
  std::array<double, types::S::size()> optimal_thrusts;
  
  {
    std::ifstream data {argv[1]};
    if(!data) {
      std::cout << "Cannot open " << argv[1] << ". Aborting." << std::endl;
      return 1;
    }
    
    double ignore;
    auto out = optimal_thrusts.begin();
    for(auto s_it = types::S::begin(); s_it != types::S::end(); ++s_it) 
      data >> ignore >> ignore >> *(out++) >> ignore >> ignore;
  }

  
  
  // Let us build up the encapsulations of our rocket.
  auto params = make_params();
  auto tgt = target(gen, MARGIN, target_period, params);
  auto rocket = types::base_continuous_system(params);

  // The relative rocket reads the current target from tgt.
  auto relative_rocket = types::continuous_system(rocket, [&tgt](){return tgt.height;});

  // The controller computes the thrust from height and speed
  // observations. To do so, it uses relative_rocket (that knows the
  // target) to convert (height, speed) into (error, speed). Then it
  // retrieves the corresponding discrete state. The index of that
  // discrete states is tne indext of the thrust value in the
  // optimal_thrust array we have loaded from previous example.
  auto controller =
    [&optimal_thrusts, &relative_rocket, dt] (const types::base_continuous_system::observation_type& obs) -> types::base_continuous_system::command_type {
      types::S current {relative_rocket.convert(obs)};
      return {.value = optimal_thrusts[static_cast<std::size_t>(current)], .duration = dt};
    };

  std::cout << std::endl;

  // Controlling the rocket is now very easy...
  
  {
    std::string filename {"rocket-orbit.dat"};
    std::ofstream datafile {filename};
    double t = 0;
    std::size_t orbit_size = std::size_t((EPISODE_DURATION)/dt);
    for(auto [observation, action, report] 
	  : gdyn::views::controller(rocket, controller) 
	  | gdyn::views::orbit(rocket)                       
	  | std::views::take(orbit_size)) {
      datafile << t << ' ' << observation.height << ' ' << tgt.height << std::endl;
      ++tgt;
      if(action) t += dt;
    }
    std::cout << "File " << filename << " generated." << std::endl;
  }

  {
    std::string filename {"rocket-orbit.plot"};
    std::ofstream plotfile {filename};

    plotfile << "plot 'rocket-orbit.dat' using 1:2 with lines lc rgb \"black\" title \"rocket height\", \\" << std::endl
	     << "'rocket-orbit.dat' using 1:3 with lines lc rgb \"red\" title \"target height\"" << std::endl;
    std::cout << std::endl
	      << "Run : gnuplot -p " << filename << std::endl
	      << std::endl
	      << std::endl;
  }

  return 0;
}
