#include <iostream>
#include <iomanip>
#include <fstream>
#include <sstream>
#include <array>
#include <random>
#include <algorithm>
#include <cstddef>

#include <gdyn.hpp>
#include <rllib2.hpp>

// Read these files.
#include "discrete-rocket-problem.hpp"
#include "my_rocket_config.hpp"

// In this example, we load the controller learned previously and apply it.

// Let us implement a moving target
struct target {
private:
  std::mt19937& gen;
  std::uniform_real_distribution<double> d;
  std::size_t period;
  std::size_t count;

public:
  double height;
  
  target(std::mt19937& gen, double margin, std::size_t period, const gdyn::problem::rocket::parameters& params)
    : gen(gen),
      d(margin, params.ceiling_height - margin),
      period(period),
      count(1) {++(*this);}

  target& operator++() {
    if(--count == 0) {
      height = d(gen);
      count = period;
    }
    return *this;
  }
};

#define TARGET_PERIOD 50
#define ORBIT_SIZE 1000
#define MARGIN 200
int main(int argc, char* argv[]) {

  if(argc != 2) {
    std::cout << "Usage: " << argv[0] << " <controller-datafile.dat>" << std::endl
	      << "       The datafile is generated by previous example." << std::endl;
    return 0;
  }
  
  std::random_device rd;
  std::mt19937 gen(rd());

  std::array<double, types::S::size()> optimal_thrusts;
  
  {
    std::ifstream data {argv[1]};
    if(!data) {
      std::cout << "Cannot open " << argv[1] << ". Aborting." << std::endl;
      return 1;
    }
    
    double ignore;
    auto out = optimal_thrusts.begin();
    for(auto s_it = types::S::begin(); s_it != types::S::end(); ++s_it) 
      data >> ignore >> ignore >> *(out++) >> ignore >> ignore;
  }

  
  
  // Let us build up the encapsulations of our rocket.
  auto params = make_params();
  auto tgt = target(gen, MARGIN, TARGET_PERIOD, params);
  auto rocket = types::base_continuous_system(params);
  auto relative_rocket = types::continuous_system(rocket, [&tgt](){return tgt.height;});
  
  auto controller =
    [&optimal_thrusts, &relative_rocket] (const types::base_continuous_system::observation_type& obs) -> types::base_continuous_system::command_type {
      types::S current {relative_rocket.convert(obs)};
      return {.value = optimal_thrusts[static_cast<std::size_t>(current)], .duration = types::dt};
    };

  std::cout << std::endl;
  {
    std::string filename {"rocket-orbit.dat"};
    std::ofstream datafile {filename};
    double t = 0;
    for(auto [observation, action, report] 
	  : gdyn::views::controller(rocket, controller) 
	  | gdyn::views::orbit(rocket)                       
	  | std::views::take(ORBIT_SIZE)) {
      datafile << t << ' ' << observation.height << ' ' << tgt.height << std::endl;
      ++tgt;
      if(action) t += action->duration;
    }
    std::cout << "File " << filename << " generated." << std::endl;
  }

  {
    std::string filename {"rocket-orbit.plot"};
    std::ofstream plotfile {filename};

    plotfile << "plot 'rocket-orbit.dat' using 1:2 with lines lc rgb \"black\" title \"rocket height\", \\" << std::endl
	     << "'rocket-orbit.dat' using 1:3 with lines lc rgb \"red\" title \"target height\"" << std::endl;
    std::cout << std::endl
	      << "Run : gnuplot -p " << filename << std::endl
	      << std::endl
	      << std::endl;
  }

  return 0;
}
